export const IPC_CHANNELS = {
  WINDOW_CLOSE: 'WINDOW_CLOSE',
  WINDOW_MAX: 'WINDOW_MAX',
  WINDOW_MIN: 'WINDOW_MIN',
  BROWSE_PAGE: 'BROWSE_PAGE',
  GET_INSTALLED_SOFTWARE: 'GET_INSTALLED_SOFTWARE',
  GET_ICON: 'GET_ICON',
  OPEN_REGEDIT: 'OPEN_REGEDIT',
  EXPORT_REGEDIT: 'EXPORT_REGEDIT',
  IMPORT_REGEDIT: 'IMPORT_REGEDIT',
  READ_REGEDIT_VALUES: 'READ_REGEDIT_VALUES',
  OPEN_PATH: 'OPEN_PATH',
  READ_JSON_FILE: 'READ_JSON_FILE',
  WRITE_JSON_FILE: 'WRITE_JSON_FILE',
  COPY_FILE: 'COPY_FILE',
} as const

export type IpcChannels = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS]


