export const IPC_CHANNELS = {
  WINDOW_CLOSE: 'WINDOW_CLOSE',
  WINDOW_MAX: 'WINDOW_MAX',
  WINDOW_MIN: 'WINDOW_MIN',
  BROWSE_PAGE: 'BROWSE_PAGE',
  GET_INSTALLED_SOFTWARE: 'GET_INSTALLED_SOFTWARE',
  GET_ICON: 'GET_ICON',
  OPEN_REGEDIT: 'OPEN_REGEDIT',
} as const

export type IpcChannels = (typeof IPC_CHANNELS)[keyof typeof IPC_CHANNELS]


